
import { useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAppContext } from "@/context/AppContext";
import { Edit, FileText, Loader2, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { UserStory } from "@/types";
import { useNavigate } from "react-router-dom";

export function UserStoryList() {
  const { userStories, isGenerating, refineStory, deleteStory } = useAppContext();
  const [selectedStoryId, setSelectedStoryId] = useState<string | null>(null);
  const [refinementText, setRefinementText] = useState("");
  const [open, setOpen] = useState(false);
  const [selectedStories, setSelectedStories] = useState<{[key: string]: boolean}>({});
  const navigate = useNavigate();

  const handleRefineStory = async () => {
    if (selectedStoryId && refinementText) {
      await refineStory(selectedStoryId, refinementText);
      setOpen(false);
      setRefinementText("");
      setSelectedStoryId(null);
    }
  };

  const handleOpenRefinement = (id: string) => {
    setSelectedStoryId(id);
    setOpen(true);
  };

  const handleAddToRally = () => {
    const storiesToAdd = userStories.filter(story => selectedStories[story.id]);
    if (storiesToAdd.length > 0) {
      // In a real app, would persist these stories to state
      // For demo, we'll navigate to the rally board
      navigate("/rally");
    }
  };

  const toggleStorySelection = (id: string) => {
    setSelectedStories(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const isAnyStorySelected = Object.values(selectedStories).some(value => value);
  
  if (userStories.length === 0) {
    return null;
  }

  return (
    <>
      <Card className="w-full mt-6 animate-fade-in">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-xl">Generated User Stories</CardTitle>
            <CardDescription>
              Review, refine or delete the user stories generated by the AI
            </CardDescription>
          </div>
          {userStories.length > 0 && (
            <Button 
              onClick={handleAddToRally} 
              variant="secondary" 
              className="bg-rally hover:bg-rally-hover text-white"
              disabled={!isAnyStorySelected}
            >
              <FileText className="mr-2 h-4 w-4" />
              Add to Rally Board
            </Button>
          )}
        </CardHeader>
        <CardContent className="grid gap-6">
          {userStories.map((story) => (
            <div
              key={story.id}
              className="story-card p-4 rounded-md grid gap-4"
            >
              <div className="flex items-start justify-between">
                <div className="flex gap-3 items-center">
                  <input
                    type="checkbox"
                    className="h-4 w-4 text-primary rounded"
                    checked={!!selectedStories[story.id]}
                    onChange={() => toggleStorySelection(story.id)}
                  />
                  <div>
                    <h3 className="font-medium text-lg flex items-center gap-2">
                      {story.name} 
                      <Badge variant="outline" className="ml-2">{story.id}</Badge>
                    </h3>
                    <p className="text-muted-foreground text-sm">
                      Plan Estimate: {story.planEstimate} points
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-2">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0"
                    onClick={() => handleOpenRefinement(story.id)}
                  >
                    <Edit className="h-4 w-4" />
                    <span className="sr-only">Refine</span>
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                    onClick={() => deleteStory(story.id)}
                  >
                    <Trash2 className="h-4 w-4" />
                    <span className="sr-only">Delete</span>
                  </Button>
                </div>
              </div>
              <div>
                <p className="text-sm font-medium">Description:</p>
                <p className="text-muted-foreground text-sm mt-1">
                  {story.description}
                </p>
              </div>
              {story.notes && (
                <div>
                  <p className="text-sm font-medium">Notes:</p>
                  <p className="text-muted-foreground text-sm mt-1">
                    {story.notes}
                  </p>
                </div>
              )}
            </div>
          ))}
        </CardContent>
      </Card>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Refine User Story</DialogTitle>
            <DialogDescription>
              Ask the AI to refine this user story with additional details or changes.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="refinement" className="text-left">
                Refinement Instructions
              </Label>
              <Textarea
                id="refinement"
                placeholder="Add more details about authentication requirements..."
                value={refinementText}
                onChange={(e) => setRefinementText(e.target.value)}
                className="min-h-[100px]"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleRefineStory} disabled={!refinementText || isGenerating}>
              {isGenerating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Refining...
                </>
              ) : (
                'Apply Refinement'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
